pombe_sigara/urls.py
from django.contrib import admin
from django.urls import path

from django.conf import settings
from django.conf.urls.static import static
from django.views.static import serve

from django.contrib.auth import views as auth_views
from core.views import home_shop, home_view, category_view, policy_page, product_view, updateItem, cart_view, checkout_view, process_order, policy_page
from core.views import manage_orders, manage_single_order, ship_order, deliver_order, signup_view, login_view, logout_view, Search, contact_view

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', home_view, name='home-view'),
    path('shop/', home_shop, name='home-shop-view'),

    path('signup/', signup_view, name='signup-view'),
    path('login/', login_view, name='login-view'),
    path('logout/', logout_view, name='logout-view'),


    path('home/', home_view, name='home-view'),
    path('shop/<str:slug>/', category_view, name='category-view'),
    path('shop-product/<str:slug>/', product_view, name='product-view'),
    path('cart/', cart_view, name='cart-view'),
    path('checkout/', checkout_view, name='checkout-view'),
    path('process_order/', process_order, name='process_order-view'),
    path('manage_orders/', manage_orders, name='manage-orders-view'),
    path('manage_orders/<str:order>', manage_single_order, name='manage-single-order-view'),
    path('manage_orders/ship/<str:order>', ship_order, name='ship-order-view'),
    path('manage_orders/deliver/<str:order>', deliver_order, name='deliver-order-view'),

    path('update_item/', updateItem, name='update-item'),
    path('products/search/', Search, name='search'),
    path('contact-us/', contact_view, name='contact'),
    path('policy/', policy_page, name='policy'),


    path('reset_password/', auth_views.PasswordResetView.as_view(template_name = "recoverpw-1.html"), name='reset_password'),
    path('reset_password_sent/', auth_views.PasswordResetDoneView.as_view(template_name = "recoverpw_sent.html"), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name = "recoverpw_set.html"), name='password_reset_confirm'),
    path('reset_password_complete/', auth_views.PasswordResetCompleteView.as_view(template_name = "recoverpw_complete.html"), name='password_reset_complete'),


]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/forms.py
from django import forms
from django.forms import ModelForm
from .models import Customer
from django.contrib.auth import get_user_model
from django.db.models import Q
from django.contrib.auth.forms import UserCreationForm



User = get_user_model()



class NewUserForm(UserCreationForm):

	
	password1 = forms.CharField(label='Password', widget=forms.PasswordInput(attrs={'class': 'form-control'}))
	password2 = forms.CharField(label='Password confirmation', widget=forms.PasswordInput(attrs={'class': 'form-control'}))

	class Meta:
		model = User
		fields = ("username", "email", "first_name", "last_name")
		widgets = {

			'username': forms.TextInput(attrs={'class': 'form-control'}),
        	'email': forms.EmailInput(attrs={'class': 'form-control'}),
        	'first_name': forms.TextInput(attrs={'class': 'form-control'}),
        	'last_name': forms.TextInput(attrs={'class': 'form-control'}),
			
		},

	def clean_password(self):
		password1 = self.cleaned_data.get('password1')
		password2 = self.cleaned_data.get('password2')
		if password1 and password2 and password1 != password2:
			raise forms.ValidationError("Passwords do not match")
		return password1

	def save(self, commit=True):
		user = super(UserCreationForm, self).save(commit=False)
		user.email = self.cleaned_data['email']
		user.set_password(self.cleaned_data['password1'])



		if commit:
			user.save()
		return user




class CustomerForm(ModelForm):
	
	class Meta:
		model = Customer
		fields = ('phone_number',)
		widgets = {

			'phone_number': forms.NumberInput(attrs={'class': 'form-control'}),
		},





class UserLoginForm(forms.Form):
	
	query = forms.CharField(label='Username / Email', widget=forms.TextInput(attrs={'class': 'form-control'}))
	password = forms.CharField(label='Password', widget=forms.PasswordInput(attrs={'class': 'form-control'}))

	def clean(self, *args, **kwargs):
		
		query = self.cleaned_data.get('query')
		password = self.cleaned_data.get('password')
		user_qs_final = User.objects.filter(
                    Q(username__iexact=query) |
                    Q(email__iexact=query)
                ).distinct()
		

		if not user_qs_final.exists() and user_qs_final.count != 1:
			raise forms.ValidationError("Invalid credentials - user does not exist")
		
		user_obj = user_qs_final.first()
		
		if not user_obj.check_password(password):
			raise forms.ValidationError("Invalid credentials - user does not exist")
			
		self.cleaned_data["user_obj"] = user_obj
		
		return super(UserLoginForm, self).clean(*args, **kwargs)




class ContactForm(forms.Form):

	name = forms.CharField(label='Name', widget=forms.TextInput(attrs={'class': 'border rounded-0 w-100 input-area name', 'placeholder':'Name' }))
	email = forms.EmailField(label='Email', widget=forms.TextInput(attrs={'class': 'border rounded-0 w-100 input-area name', 'placeholder':'Email'}))
	subject = forms.CharField(label='Subject', widget=forms.TextInput(attrs={'class': 'border rounded-0 w-100 input-area name', 'placeholder':'Subject'}))
	message = forms.CharField(widget=forms.Textarea(attrs={'class': 'border rounded-0 w-100 custom-textarea input-area', 'placeholder':'Message', 'cols':30, 'rows':5}))

templates/category.html
{% extends 'base.html' %}
{% load static %}
{% load humanize %}


{% block content %}



    <div class="row">
        <div class="col-12 text-center">
            <div class="breadcrumb-content position-relative section-content">
                <h3 class="title-3">{{category.name}}</h3>
            </div>
        </div>
    </div>


    <!-- Shop Main Area Start Here -->
    <div class="shop-main-area">
        <div class="container container-default custom-area">
            <div class="row flex-row-reverse">

                <div class="col-lg-9 col-12 col-custom widget-mt">

                    <!--shop toolbar start-->
                    <div class="shop_toolbar_wrapper">
                        <div class="shop_toolbar_btn">
                            <button data-role="grid_3" type="button" class="active btn-grid-3" data-toggle="tooltip" title="3"><i class="fa fa-th"></i></button>
                            <!-- <button data-role="grid_4" type="button"  class=" btn-grid-4" data-toggle="tooltip" title="4"></button> -->
                            <button data-role="grid_list" type="button" class="btn-list" data-toggle="tooltip" title="List"><i class="fa fa-th-list"></i></button>
                        </div>
                    </div>
                    <!--shop toolbar end-->

                    <!-- Shop Wrapper Start -->
                    <div class="row shop_wrapper grid_3">
                        {% for product in products %}
                        <div class="col-md-6 col-sm-6 col-lg-4 col-custom product-area">
                            
                            <div class="single-product position-relative">
                                
                                <div class="product-image">
                                    <a class="d-block" href="{% url 'product-view' product.slug %}">
                                        <img src="{{product.image.url}}" alt="" class="product-image-1 w-100">
                                        <img src="{{product.image.url}}" alt="" class="product-image-2 position-absolute w-100">
                                    </a>
                                </div>
                                <div class="product-content">
                                    <div class="product-rating">
                                        <i class="fa fa-star"></i>
                                        <i class="fa fa-star"></i>
                                        <i class="fa fa-star"></i>
                                        <i class="fa fa-star-o"></i>
                                        <i class="fa fa-star-o"></i>
                                    </div>
                                    <div class="product-title">
                                        <h4 class="title-2"> <a href="{% url 'product-view' product.slug %}">{{product.name}}</a></h4>
                                    </div>
                                    <div class="price-box">
                                        <span class="regular-price ">Ksh {{product.old_price|intcomma}}</span>
                                        <span class="old-price"><del>Ksh {{product.new_price|intcomma}}</del></span>
                                    </div>
                                </div>
                                <div class="add-action d-flex position-absolute">
                                    <a data-product="{{product.id}}" data-action="add" class="add-to-store" title="Add To cart">
                                        <i class="ion-bag"></i>
                                    </a>
                                    <a href="wishlist.html" title="Add To Wishlist">
                                        <i class="ion-ios-heart-outline"></i>
                                    </a>
                                </div>
                                

                                <div class="product-content-listview">
                                    <div class="product-rating">
                                        <i class="fa fa-star"></i>
                                        <i class="fa fa-star"></i>
                                        <i class="fa fa-star"></i>
                                        <i class="fa fa-star-o"></i>
                                        <i class="fa fa-star-o"></i>
                                    </div>
                                    <div class="product-title">
                                        <h4 class="title-2"> <a href="{% url 'product-view' product.slug %}">{{product.name}}</a></h4>
                                    </div>
                                    <div class="price-box">
                                        <span class="regular-price ">Ksh {{product.old_price|intcomma}}</span>
                                        <span class="old-price"><del>Ksh {{product.new_price|intcomma}}</del></span>
                                    </div>
                                    <div class="add-action-listview d-flex">
                                        <a data-product="{{product.id}}" data-action="add" class="add-to-store" title="Add To cart">
                                            <i class="ion-bag"></i>
                                        </a>
                                        <a href="wishlist.html" title="Add To Wishlist">
                                            <i class="ion-ios-heart-outline"></i>
                                        </a>
                                    </div>
                                    
                                </div>
                                
                            </div>
                            
                        
                        </div>
                        {% endfor %}
                    </div>
                    <!-- Shop Wrapper End -->
                    

                    <!-- Bottom Toolbar Start -->
                    <div class="row">
                        <div class="col-sm-12 col-custom">
                            <div class="toolbar-bottom mt-30">
                                <nav class="pagination pagination-wrap mb-10 mb-sm-0">
                                    <ul class="pagination">
                                        {% if products.has_previous %}
                                            <li><a href="?page={{ products.previous_page_number }}"><i class="fa fa-chevron-left" aria-hidden="true"></i></a></li>
                                        {% else %}
                                            <li class="disabled"><span><i class="fa fa-chevron-left" aria-hidden="true"></i></span></li>
                                        {% endif %}

                                        {% if products.number|add:'-4' > 1 %}
                                            <li><a href="?page={{ products.number|add:'-5' }}">&hellip;</a></li>
                                        {% endif %}

                                        {% for i in products.paginator.page_range %}
                                            {% if products.number == i %}
                                                <li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
                                            {% elif i > products.number|add:'-5' and i < products.number|add:'5' %}
                                                <li><a href="?page={{ i }}">{{ i }}</a></li>
                                            {% endif %}
                                        {% endfor %}

                                        {% if products.paginator.num_pages > products.number|add:'4' %}
                                            <li><a href="?page={{ products.number|add:'5' }}">&hellip;</a></li>
                                        {% endif %}

                                        {% if products.has_next %}
                                            <li><a href="?page={{ products.next_page_number }}"><i class="fa fa-chevron-right" aria-hidden="true"></i></a></li>
                                        {% else %}
                                            <li class="disabled"><span><i class="fa fa-chevron-right" aria-hidden="true"></i></span></li>
                                        {% endif %}
                                    </ul>
                                </nav>
                                <!-- <p class="desc-content text-center text-sm-right">Showing 1 - 12 of 34 result</p> -->
                            </div>
                        </div>
                    </div>
                    <!-- Bottom Toolbar End -->
                </div>


                <div class="col-lg-3 col-12 col-custom">
                    <!-- Sidebar Widget Start -->
                    <aside class="sidebar_widget widget-mt">
                        <div class="widget_inner">
                            <div class="widget-list widget-mb-1">
                                <h3 class="widget-title">Search</h3>
                                <div class="search-box">
                                    <form method="GET" action="{% url 'search' %}">
                                        <div class="input-group">
                                            <input type="text" class="form-control" placeholder="Search Our Store" aria-label="Search Our Store" name="query">
                                            <div class="input-group-append">
                                                <button class="btn btn-outline-secondary" type="submit">
                                                    <i class="fa fa-search"></i>
                                                </button>
                                            </div>
                                        </div>
                                    </form>
                                </div>
                            </div>
                            
                            <div class="widget-list widget-mb-1">
                                <h3 class="widget-title">Categories</h3>
                                <div class="sidebar-body">
                                    <ul class="sidebar-list">
                                        {% for cat in all_categories %}
                                        <li><a href="{% url 'category-view' cat.slug %}">{{cat.name}}</a></li>
                                        {% endfor %}
                                    </ul>
                                </div>
                            </div>
                            
                            
                            
                        </div>
                    </aside>
                    <!-- Sidebar Widget End -->
                </div>
                
            </div>
        </div>
        <!-- Shop Main Area End Here -->
    </div>


{% endblock %}

templates/contact-us.html
{% extends 'base.html' %}
{% load static %}
{% load humanize %}


{% block content %}


    <!-- Contact Us Area Start Here -->
    <div class="contact-us-area">
        <div class="container container-default-2 custom-area">
            
            <div class="row">
                <div class="col-md-12 col-custom">
                    <form method="POST" action="." accept-charset="UTF-8" class="contact-form">
                        {% csrf_token %}
                        <div class="comment-box mt-5">
                            <h5 class="text-uppercase">Get in Touch</h5>
                            <div class="row mt-3">
                                <div class="col-md-6 col-custom">
                                    <div class="input-item mb-4">
                                        {{form.name}}
                                    </div>
                                </div>
                                <div class="col-md-6 col-custom">
                                    <div class="input-item mb-4">
                                        {{form.email}}
                                    </div>
                                </div>
                                <div class="col-12 col-custom">
                                    <div class="input-item mb-4">
                                        {{form.subject}}
                                    </div>
                                </div>
                                <div class="col-12 col-custom">
                                    <div class="input-item mb-4">
                                        {{form.message}}
                                    </div>
                                </div>
                                <div class="col-12 col-custom mt-40">
                                    <button type="submit" name="submit" class="btn obrien-button primary-btn rounded-0 mb-0">Send A Message</button>
                                </div>
                                <p class="col-12 col-custom form-message mb-0"></p>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
    <!-- Contact Us Area End Here -->
    

{% endblock %}

templates/home.html
{% extends 'base.html' %}
{% load static %}
{% load humanize %}


{% block home %}


    <!-- Begin Slider Area One -->
    <div class="slider-area ">
        <div class="obrien-slider arrow-style" data-slick-options='{
        "slidesToShow": 1,
        "slidesToScroll": 1,
        "infinite": true,
        "arrows": true,
        "dots": true,
        "autoplay" : true,
        
        "fade" : true,
        "autoplaySpeed" : 5000,
        "pauseOnHover" : false,
        "pauseOnFocus" : false
        }' data-slick-responsive='[
        {"breakpoint":992, "settings": {
        "slidesToShow": 1,
        "arrows": false,
        "dots": true
        }}
        ]'>

            <a href="" class="slide-item slide-3 bg-position slide-bg-1 animation-style-01 position-relative">
                <div class="slider-content">
                    <div class="col-6">
                    </div>
                </div>
            </a>

            <a href="" class="slide-item slide-4 bg-position slide-bg-1 animation-style-01 position-relative">
                <div class="slider-content">
                    
                </div>
            </a>

            <a href=""class="slide-item slide-2 bg-position slide-bg-1 animation-style-01 position-relative">
                <div class="slider-content">
                    
                </div>
            </a>

        </div>
    </div>
    <!-- Slider Area One End Here -->

    <!-- Call To Action Area Start Here -->
    <div class="call-to-action-area">
        <div class="container container-default custom-area">
            <div class="row">
                
            </div>
        </div>
    </div>
    <!-- Call to Action Area End Here -->

    <!-- Banner Area Start Here -->
    <div class="banner-area mt-12">
        <div class="container container-default custom-area">
            <div class="row">
                {% for cat in all_categories %}
                <div class="col-md-4 col-sm-12 col-custom mb-4">
                    <div class="banner-image hover-style">
                        <a class="d-block" href="{% url 'category-view' cat.slug %}">
                            <img class="w-100" src="{{cat.imageUrl}}" alt="Banner Image">
                        </a>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
    </div>
    <!-- Banner Area End Here -->


{% endblock %}

templates/login.html

{% extends 'base.html' %}
{% load static %}
{% load humanize %}


{% block content %}



    <div class="row">
        <div class="col-12 text-center">
            <div class="breadcrumb-content position-relative section-content">
                <h3 class="title-3">Login</h3>
                <ul>
                    <li><a href="index.html">Home</a></li>
                    <li>Login</li>
                </ul>
            </div>
        </div>
    </div>



    <!-- Login Area Start Here -->
    <div class="login-register-area mt-no-text mb-no-text">
        <div class="container container-default-2 custom-area">
            <div class="row">
                <div class="col-lg-6 offset-lg-3 col-md-8 offset-md-2 col-custom">
                    <div class="login-register-wrapper">
                        <div class="section-content text-center mb-5">
                            <h2 class="title-4 mb-2">Login</h2>
                            <p class="desc-content">Please log-in using your account details below.</p>
                        </div>
                        <form action="." method="POST">
                            {% csrf_token %}

                            <div class="single-input-item mb-3">
                                <label for="username">Username / Email</label>
                                {{ form.query }}
                            </div>
                            <div class="single-input-item mb-3">
                                <label for="userpassword">Password</label>
                                {{ form.password }}
                            </div>

                            {% if form.errors %}
                                    {% for field in form %}
                                        {% for error in field.errors %}
                                            <div class="alert alert-danger">
                                                <strong>{{ field.label }} : </strong><span>{{ error|escape }}</strong>
                                            </div>
                                        {% endfor %}
                                    {% endfor %}
                                    {% for error in form.non_field_errors %}
                                        <div class="alert alert-danger">
                                            <strong>{{ error|escape }}</strong>
                                        </div>
                                    {% endfor %}
                                {% endif %}

                            <div class="single-input-item mb-3">
                                <div class="login-reg-form-meta d-flex align-items-center justify-content-between">
                                    <div class="remember-meta mb-3">
                                        <div class="custom-control custom-checkbox">
                                            <input type="checkbox" class="custom-control-input" id="rememberMe">
                                            <label class="custom-control-label" for="rememberMe">Remember Me</label>
                                        </div>
                                    </div>
                                    <a href="{% url 'reset_password' %}" class="forget-pwd mb-3">Forgot Password?</a>
                                </div>
                            </div>
                            <div class="single-input-item mb-3">
                                <button class="btn obrien-button-2 primary-color" type="submit">Login</button>
                            </div>
                            <div class="single-input-item">
                                <a href="{% url 'signup-view' %}">Create Account</a>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Login Area End Here -->
       

{% endblock %}

templates/policy.html
{% extends 'base.html' %}
{% load static %}
{% load humanize %}


{% block content %}

<!--faq area start-->
<div class="faq_content_area">
    <div class="container">
        <div class="row">
            <div class="col-12">
                <div class="faq_content_wrapper">
                    <h1>Pombe Sigara Policy Statement</h1>
                    <br>
                    <br>
                    <br>
                    <h5>Data Privacy & Collection of Information</h5>
                    <br>
                    <p>We collect your personal information with your knowledge and consent when you do any of the following (please note that this list is not exhaustive):
                        <br>
                        <br>
                        <p class="ml-3">•	Register for an account with Pombe Sigara.</p>
                        <br>
                        <p class="ml-3">•	Pay for products & services via FinTech or traditional bank services.</p>
                        <br>
                        <p class="ml-3">•	Subscribe to our premium rates services, short message service, email or social media platforms;</p>
                        <br>
                        <p class="ml-3">•	Ask us for more information about a product or service or contact us with a query or complaint;</p>
                        <br>
                        <p class="ml-3">•	Respond to or participate in a survey, marketing promotion, prize competition or special offer;</p>
                        <br>
                        <p class="ml-3">•	Visit, access or use our website or third-party social media websites & pages;</p>
                        <br>
                        <p class="ml-3">•	We may also collect your information from other organisations including credit-reference bureaus, fraud prevention agencies and business directories;</p>
                        <br>
                        <p class="ml-3">•	We may collect your information when you interact with us as a supplier, agent, merchant or dealer as prescribed in this statement;</p>
                        <br>
                        <p class="ml-3">•	We also collect information when you visit any of our premises.</p>
                    </p>

                    <br>
                    <br>
                    <h5>Age & Health</h5>
                    <p>
                        <br>
                        <p>•	Alcohol & Cigarettes will not be sold to persons under the age of 18..</p>
                        <br>
                        <p>•	Please do not share with anyone under the legal purchase age for alcohol.</p>
                        <br>
                        <p>•	Drink Responsibly.</p>
                        <br>
                        <p>•	Consumption of alcoholic beverages impairs your ability to drive a car or operate machinery, and may cause health problems.</p>
                        <br>
                        <p>•	Smoking Causes Lung Cancer, Heart Disease, Emphysema, and May Complicate Pregnancy.</p>
                        <br>
                        <p>•	If interested in learning more about responsible drinking, visit <a href="https://www.drinkiq.com/" target="blank"><strong>www.DRINKiQ.com</strong></a>.</p>
                        <br>
                    </p>


                    <br>
                    <br>
                    <h5>Other Relevant Policies</h5>
                    <br>
                    <p>•	Pombe Sigara is committed to the highest standards of corporate governance and business ethics. We have instituted systems to ensure that 
                        high standards of corporate governance are maintained at all levels of the organisation and is in compliance with relevant laws.
                    </p>
                    <br>
                    <p>•	We do not onboard minors (any person under 18 years of age). If you allow a minor to use our services, you should be aware that you may be 
                        held accountable and found liable of a criminal offence.
                    </p>

                </div>
            </div>
        </div>
    </div>
</div>


{% endblock %}

templates/recoverpw-1.html
{% extends "base.html" %}
{% load static %}

{% block content %}

<div class="home-btn d-none d-sm-block">
    <a href="{% url 'home-shop-view' %}" target="_blank" class="text-dark"><i class="fas fa-home h2"></i></a>
</div>
<div class="account-pages my-5 pt-5">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8 col-lg-6 col-xl-5">
                <div class="login-register-wrapper">
                    <div class="section-content text-center mb-5">
                        <a href="{% url 'home-shop-view' %}" target="_blank" class="logo logo-admin">
                            <img class="" src="{% static '/assets/images/logo/logo-pombesigara.png' %}" height="50" alt="logo">
                        </a>
                        <h5 class="text-dark font-size-20 p-2 mt-4">Reset Password</h5>
                        
                    </div>

                    <div class="alert alert-success mt-5" role="alert">
                        Enter your Email and instructions will be sent to you!
                    </div>


                    <form class="form-horizontal mt-4" method="POST" action=".">

                        {% csrf_token %}

                        
                        <div class="single-input-item mb-3">
                            <label for="id_email">Email</label>
                            <input class="form-control" type="email" name="email" autocomplete="email" maxlength="254" required="" id="id_email">
                        </div>

                        <div>
                            <div class="single-input-item mb-3">
                                <button class="btn obrien-button-2 primary-color mt-4" type="submit">Reset Password</button>
                            </div>

                            <p>Remember It ? <a href="{% url 'login-view'%}" class="font-weight-medium text-primary"> Sign In here </a> </p>
                        </div>

                    </form>


                </div>

            </div>
        </div>
    </div>
</div>

{% endblock %}